import "./lexical-theme.css";

export const theme = {
  paragraph: "finest-paragraph",
  quote: "finest-quote",
  heading: {
    h1: "finest-heading-h1",
    h2: "finest-heading-h2",
    h3: "finest-heading-h3",
    h4: "finest-heading-h4",
    h5: "finest-heading-h5",
    h6: "finest-heading-h6",
  },
  list: {
    nested: {
      listitem: "finest-nested-listitem",
    },
    ol: "finest-list-ol",
    ul: "finest-list-ul",
    listitem: "finest-listItem",
    listitemChecked: "finest-listItemChecked",
    listitemUnchecked: "finest-listItemUnchecked",
  },
  hashtag: "finest-hashtag",
  image: "finest-image",
  link: "finest-link",
  text: {
    bold: "finest-textBold",
    code: "finest-textCode",
    italic: "finest-textItalic",
    strikethrough: "finest-textStrikethrough",
    subscript: "finest-textSubscript",
    superscript: "finest-textSuperscript",
    underline: "finest-textUnderline",
    underlineStrikethrough: "finest-textUnderlineStrikethrough",
  },
  code: "finest-code",
  codeHighlight: {
    atrule: "finest-tokenAttr",
    attr: "finest-tokenAttr",
    boolean: "finest-tokenProperty",
    builtin: "finest-tokenSelector",
    cdata: "finest-tokenComment",
    char: "finest-tokenSelector",
    class: "finest-tokenFunction",
    "class-name": "finest-tokenFunction",
    comment: "finest-tokenComment",
    constant: "finest-tokenProperty",
    deleted: "finest-tokenProperty",
    doctype: "finest-tokenComment",
    entity: "finest-tokenOperator",
    function: "finest-tokenFunction",
    important: "finest-tokenVariable",
    inserted: "finest-tokenSelector",
    keyword: "finest-tokenAttr",
    namespace: "finest-tokenVariable",
    number: "finest-tokenProperty",
    operator: "finest-tokenOperator",
    prolog: "finest-tokenComment",
    property: "finest-tokenProperty",
    punctuation: "finest-tokenPunctuation",
    regex: "finest-tokenVariable",
    selector: "finest-tokenSelector",
    string: "finest-tokenSelector",
    symbol: "finest-tokenProperty",
    tag: "finest-tokenProperty",
    url: "finest-tokenOperator",
    variable: "finest-tokenVariable",
  },
};
